# fly.toml app configuration file generated for emptybot on 2025-08-12T12:11:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emptybot'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[env]
  TZ = "Asia/Tbilisi"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

[processes]
  worker = "java -jar /app/app.jar --mode=worker"
